import { palette } from "./palette";

export const typography = {
  h1: {
    fontFamily: "Nunito",
    color: palette.text.darkBlack,
    fontWeight: 700,
    fontSize: "20px",
    fontStretch: "normal",
    textAlign: "left",
    fontStyle: "normal",
    lineHeight: 1.23,
    letterSpacing: "0.05em",
    textTransform: "capatalize",
  },
  h2: {
    fontFamily: "Nunito",
    color: palette.text.darkBlack,
    fontWeight: 700,
    fontSize: "15px",
    lineHeight: "14.52px",
  },

  h3: {
    fontFamily: "Nunito",
    color: "rgba(255, 255, 255, 0.87)",
    fontWeight: 300,
    fontSize: 14,
    fontStretch: "normal",
    textAlign: "left",
    fontStyle: "normal",
    lineHeight: 1.23,
    letterSpacing: "0.05em",
  },
  h4: {
    fontFamily: "Nunito",
    color: palette.gray,
    fontWeight: 600,
    fontSize: "16px",
    letterSpacing: "0.05em",
    lineHeight: 2,
    textAlign: "center",
    opacity: 0.5,
  },
  h5: {
    fontFamily: "Silka-Bold",
    color: palette.primary.lightBlue,
    fontWeight: 700,
    fontSize: "14px",
    fontStyle: "normal",
    lineHeight: 2.14,
  },
  h6: {
    fontFamily: "Nunito",
    color: palette.text.darkBlack,
    fontWeight: 500,
    fontSize: "17px",
    textTransform: "capitalize",
  },
  subtitle1: {
    fontFamily: "Nunito",
    color: palette.text.lightBlack,
    fontSize: "16px",
    fontWeight: 400,
    fontStretch: "normal",
    fontStyle: "normal",
    letterSpacing: "0.05em",
  },
  subtitle2: {
    fontFamily: "Nunito",
    color: palette.text.primary,
    fontWeight: "normal",
    fontSize: "15px",
    letterSpacing: "0.05em",
    lineHeight: 1.62,
  },
  body1: {
    fontFamily: "Nunito",
    color: palette.text.lightBlack,
    fontSize: "14px",
    fontWeight: 500,

    textAlign: "right",
  },
  body2: {
    fontFamily: "Nunito",
    color: palette.text.secondary,
    fontSize: "12px",
    letterSpacing: "-0.04px",
    lineHeight: "18px",
  },
  button: {
    fontFamily: "Nunito",
    color: palette.text.primary,
    fontSize: "14px",
  },
  caption: {
    fontFamily: "Nunito",
    color: palette.text.darkBlack,
    fontWeight: 400,
    fontSize: "12px",
    lineHeight: "14.52px",
  },
  overline: {
    fontFamily: "Nunito",
    color: palette.text.secondary,
    fontSize: "11px",
    fontWeight: 400,
    letterSpacing: "0.05em",
  },
};
